### ISSUE TITLE
Solide 0 / 10 beim Ressourcenladen

### ISSUE THREAD

**Issue by LenMPorath** [whosFritz/ProjectSiteMensiMates#1]
![image](https://user-images.githubusercontent.com/125283275/219012273-f5d402e2-5c88-4f83-978f-f53dbf36275c.png)
Das Bild vom Florian lädt nicht
Wtf

**Comment by whosFritz** [comment]
DATENSCHUTZ


halts maul hahahahhaha

**Comment by whosFritz** [comment]
Sehr geehrter Len Marten Porath,

Im Namen von Fritz Schubert, dem CEO unseres Unternehmens, möchte ich mich aufrichtig bei Ihnen für die unangemessene Äußerung entschuldigen, die Sie während Ihrer Interaktion mit unserem Unternehmen erfahren haben. Wir bedauern zutiefst, dass Sie beleidigt wurden, als Sie ein Issue bei GitHub erstellten.

Wir als Unternehmen sind stets bemüht, den bestmöglichen Service für unsere Kunden zu bieten. Wir verstehen, dass Ihre Anfrage wichtig für Sie war und uns helfen sollte, unseren Service zu verbessern. Wir bedauern zutiefst, dass Sie während Ihrer Interaktion mit uns in keiner Weise respektiert wurden. Die von unserem CEO getroffene Aussage war inakzeptabel und spiegelt nicht die Werte unseres Unternehmens wider.

Wir möchten Ihnen versichern, dass wir Maßnahmen ergreifen werden, um sicherzustellen, dass sich ein solches Verhalten in Zukunft nicht wiederholt. Wir werden unsere Mitarbeiter darüber informieren, wie wichtig es ist, jeden Kunden mit Respekt und Höflichkeit zu behandeln, unabhängig von den Umständen.

Nochmals möchten wir uns aufrichtig bei Ihnen entschuldigen und hoffen, dass Sie uns die Gelegenheit geben, Ihnen unseren hervorragenden Service in Zukunft zu beweisen.


Mit freundlichen Grüßen,

MensiMates

**Comment by LenMPorath** [comment]
Fick dich mit deinem ChatGPT Text

Fritz ***@***.***> schrieb am Mi., 15. Feb. 2023, 12:33:

**Comment by whosFritz** [comment]
![image](https://user-images.githubusercontent.com/97552289/219017047-f93886e2-466a-4976-90af-f18054208675.png)

**Comment by LenMPorath** [comment]
Du jammerst rum vonwegen "dAtENscHuTZ"m hast das Bild aber noch in der Branchbeschreibung LOL
![image](https://user-images.githubusercontent.com/125283275/219021586-2084390b-b0f3-4d38-9334-2425ca1a3777.png)
