### ISSUE TITLE
Auffordern zum Entfernen meines Bildes

### ISSUE THREAD

**Issue by LenMPorath** [whosFritz/ProjectSiteMensiMates#7]
Hallo,

es ist noch ein Bild von mir enthalten, und man kann es immer noch hier auf GitHub aufrufen.

![image](https://user-images.githubusercontent.com/125283275/223468010-acd48f0f-974d-48dc-8910-e4ed9f80c2cf.png)

Da ich nicht mehr mit diesem Projekt assoziiert werden möchte, bitte ich Sie darum mein Bild zu entfernen.
Ich berufe mich dabei auf das Recht eigenen Bildes und auf das Urheberrecht!

MfG

Len

**Comment by whosFritz** [comment]
Klaro, wird gemacht
